// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.appdunes.shopping.domain;

import com.appdunes.shopping.domain.ShoppingList;
import com.appdunes.shopping.domain.ShoppingListDataOnDemand;
import com.appdunes.shopping.domain.ShoppingListIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ShoppingListIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ShoppingListIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ShoppingListIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ShoppingListIntegrationTest: @Transactional;
    
    @Autowired
    private ShoppingListDataOnDemand ShoppingListIntegrationTest.dod;
    
    @Test
    public void ShoppingListIntegrationTest.testCountShoppingLists() {
        Assert.assertNotNull("Data on demand for 'ShoppingList' failed to initialize correctly", dod.getRandomShoppingList());
        long count = ShoppingList.countShoppingLists();
        Assert.assertTrue("Counter for 'ShoppingList' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ShoppingListIntegrationTest.testFindShoppingList() {
        ShoppingList obj = dod.getRandomShoppingList();
        Assert.assertNotNull("Data on demand for 'ShoppingList' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ShoppingList' failed to provide an identifier", id);
        obj = ShoppingList.findShoppingList(id);
        Assert.assertNotNull("Find method for 'ShoppingList' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ShoppingList' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ShoppingListIntegrationTest.testFindAllShoppingLists() {
        Assert.assertNotNull("Data on demand for 'ShoppingList' failed to initialize correctly", dod.getRandomShoppingList());
        long count = ShoppingList.countShoppingLists();
        Assert.assertTrue("Too expensive to perform a find all test for 'ShoppingList', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ShoppingList> result = ShoppingList.findAllShoppingLists();
        Assert.assertNotNull("Find all method for 'ShoppingList' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ShoppingList' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ShoppingListIntegrationTest.testFindShoppingListEntries() {
        Assert.assertNotNull("Data on demand for 'ShoppingList' failed to initialize correctly", dod.getRandomShoppingList());
        long count = ShoppingList.countShoppingLists();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ShoppingList> result = ShoppingList.findShoppingListEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ShoppingList' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ShoppingList' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ShoppingListIntegrationTest.testFlush() {
        ShoppingList obj = dod.getRandomShoppingList();
        Assert.assertNotNull("Data on demand for 'ShoppingList' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ShoppingList' failed to provide an identifier", id);
        obj = ShoppingList.findShoppingList(id);
        Assert.assertNotNull("Find method for 'ShoppingList' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyShoppingList(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'ShoppingList' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ShoppingListIntegrationTest.testMergeUpdate() {
        ShoppingList obj = dod.getRandomShoppingList();
        Assert.assertNotNull("Data on demand for 'ShoppingList' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ShoppingList' failed to provide an identifier", id);
        obj = ShoppingList.findShoppingList(id);
        boolean modified =  dod.modifyShoppingList(obj);
        Integer currentVersion = obj.getVersion();
        ShoppingList merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ShoppingList' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ShoppingListIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'ShoppingList' failed to initialize correctly", dod.getRandomShoppingList());
        ShoppingList obj = dod.getNewTransientShoppingList(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ShoppingList' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ShoppingList' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'ShoppingList' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ShoppingListIntegrationTest.testRemove() {
        ShoppingList obj = dod.getRandomShoppingList();
        Assert.assertNotNull("Data on demand for 'ShoppingList' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ShoppingList' failed to provide an identifier", id);
        obj = ShoppingList.findShoppingList(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'ShoppingList' with identifier '" + id + "'", ShoppingList.findShoppingList(id));
    }
    
}
